extern const GeoLayout yellow_coin_geo[];
extern Lights1 yellow_coin_f3dlite_material_lights;
extern u8 yellow_coin_peppermint_ci8[];
extern u8 yellow_coin_peppermint_ci8_pal_rgba16[];
extern Vtx yellow_coin_Cylinder_mesh_layer_1_vtx_0[56];
extern Gfx yellow_coin_Cylinder_mesh_layer_1_tri_0[];
extern Gfx mat_yellow_coin_f3dlite_material[];
extern Gfx mat_revert_yellow_coin_f3dlite_material[];
extern Gfx yellow_coin_Cylinder_mesh_layer_1[];
extern Gfx yellow_coin_material_revert_render_settings[];
